#include <iostream>
using namespace std;
main() {
 cout<<"Enter the Movie Name: ";
 string name;
 cin>> name;
 cout<<"Enter the Adult ticket price: ";
 int a_ticket;
 cin>> a_ticket;
 cout<<"Enter the Child ticket price: ";
 int c_ticket;
 cin>> c_ticket;
 cout<<"Enter the number of adult tickets sold: ";
 int a_sold;
 cin>> a_sold;
 cout<<"Enter the numebr of Child tickets sold: ";
 int c_sold;
 cin>> c_sold;
 cout<<"Enter the percentage of amount donated to charirty:  ";
 int donation;
 cin>> donation;
 cout<<"Movie Name: "<<name <<endl;
 int total = a_ticket*a_sold + c_ticket*c_sold;
 int donated = total%donation;
 cout<<"Total amount generated by Ticket sales: $"<<total <<endl;
 cout<<"Donation to charity ("<<donation<<"%): $"<<donated <<endl;
 int remaining = total - donated;
 cout<<"Remaining amount after Donation: "<<remaining;
}